### ISSUE TITLE
 BEGIN {print (2,97+0,94)/2}  syntax error

### ISSUE THREAD

**Issue by Guzya** [Azmodey/pg_dba_scripts#1]
Здравствуйте!
При запуске pg_database_activity.sh  вылетает ошибка

awk: cmd. line:1: BEGIN {print (2,97+0,94)/2}
awk: cmd. line:1:                         ^ syntax error
awk: cmd. line:1: BEGIN {print (2,97+0,94)/2}
awk: cmd. line:1:                          ^ unterminated regexp
awk: cmd. line:1: BEGIN {print (2,97+0,94)/2}
awk: cmd. line:1:                            ^ unexpected newline or end of string

Поправил (докинул sed с заменой запятой на точку):
if [[ $PLATFORM == "Debian GNU/Linux" ]]; then
  IOSTAT_R_AWAIT=`iostat -d -x -g ALL | grep ALL | tr -s " " | cut -d " " -f 11 | sed 's/,/./g'`
  IOSTAT_W_AWAIT=`iostat -d -x -g ALL | grep ALL | tr -s " " | cut -d " " -f 12 | sed 's/,/./g'`
  IOSTAT_UTIL=`iostat -d -x -g ALL | grep ALL | tr -s " " | cut -d " " -f 17 | sed 's/,/./g'`

  IOSTAT_AWAIT=`awk "BEGIN {print ($IOSTAT_R_AWAIT+$IOSTAT_W_AWAIT)/2}"`

**Comment by Azmodey** [comment]
Спасибо за найденную ошибку и её вариант исправления. Новая версия скриптов уже на подходе. В какой версии Debian и в какой оболочке (echo $SHELL) возникла эта ошибка? У меня iostat в Debian 10 выводит числа с точкой, тоже самое в CentOS 7 и Ubuntu 20.04.

**Comment by Guzya** [comment]
# echo $SHELL
/bin/bash

# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by Guzya** [comment]
# locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

**Comment by Azmodey** [comment]
Да, спасибо, теперь понятно. У меня локаль en_US.UTF-8

**Comment by Azmodey** [comment]
Выпущена [исправленная версия 1.10.0](https://github.com/Azmodey/pg_dba_scripts/releases/tag/1.10.0)

**Comment by Guzya** [comment]
Спасибо!
